# 🚀 Porta dinâmica (Render exige isso)
server.port=${PORT:10000}

# 🗄️ Banco via variáveis (boa prática)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# 🔌 Driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# 🧠 Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 🔍 Log (debug controlado)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true